# Generated by Django 5.2.1 on 2025-05-19 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion_corta', models.TextField(blank=True, help_text='Descripción breve para el pop-up del mapa.', null=True)),
                ('foto_iconica_url', models.URLField(blank=True, help_text='URL/path de la foto icónica para el pop-up.', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lugares',
                'unique_together': {('latitud', 'longitud')},
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField(max_length=500)),
                ('fecha_toma', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('palabras_clave', models.CharField(blank=True, help_text='Separadas por comas.', max_length=255, null=True)),
                ('es_foto_principal_lugar', models.BooleanField(default=False, help_text='Indica si esta es la foto icónica principal del Lugar (para el pop-up). Considerar lógica para asegurar solo una.')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='travel_api.lugar')),
            ],
            options={
                'ordering': ['-fecha_toma'],
            },
        ),
        migrations.CreateModel(
            name='EntradaDeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField(help_text='Soporta Markdown o texto enriquecido. El frontend deberá interpretarlo.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lugar_asociado', models.ForeignKey(blank=True, help_text='Lugar principal al que se refiere esta entrada, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_blog', to='travel_api.lugar')),
            ],
            options={
                'verbose_name_plural': 'Entradas de Blog',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
