# Generated by Django 5.2.1 on 2025-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0002_fotografia_autor_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='direccion_captura',
            field=models.TextField(blank=True, help_text='Dirección textual o descripción de la ubicación donde se tomó la foto.', null=True),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL/path del thumbnail de la fotografía.', max_length=550, null=True),
        ),
    ]
