# Generated by Django 5.2.1 on 2025-05-20 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0003_fotografia_direccion_captura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal para la fotografía.', unique=True),
        ),
    ]
