# Generated by Django 4.2.21 on 2025-06-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0004_fotografia_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'ordering': ['entrada_blog', 'orden_en_entrada', '-fecha_toma']},
        ),
        migrations.AddField(
            model_name='fotografia',
            name='entrada_blog',
            field=models.ForeignKey(blank=True, help_text='Entrada de blog a la que pertenece esta fotografía.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='travel_api.entradadeblog'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='orden_en_entrada',
            field=models.PositiveIntegerField(default=0, help_text='Orden de la fotografía dentro de la entrada de blog.'),
        ),
    ]
