# Generated by Django 4.2.21 on 2025-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0005_alter_fotografia_options_fotografia_entrada_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadeblog',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve de la entrada de blog para mostrar en el hero.', null=True),
        ),
    ]
