# Generated by Django 4.2.21 on 2025-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0006_entradadeblog_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadeblog',
            name='contenido_html',
            field=models.TextField(blank=True, help_text='Contenido convertido automáticamente a HTML desde Markdown. No editar manualmente.', null=True),
        ),
        migrations.AddField(
            model_name='entradadeblog',
            name='contenido_markdown',
            field=models.TextField(blank=True, help_text='Contenido en formato Markdown. Soporta títulos, negritas, cursivas, enlaces, listas, código, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='entradadeblog',
            name='contenido',
            field=models.TextField(blank=True, help_text='Campo temporal para migración. Usar contenido_markdown.', null=True),
        ),
    ]
