# Generated by Django 4.2.21 on 2025-06-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0008_migrate_content_to_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal de la fotografía', null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail de la fotografía (se genera automáticamente si no se especifica)', null=True, upload_to='photos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='thumbnail_url',
            field=models.CharField(blank=True, help_text='URL del thumbnail generada automáticamente', max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='url_imagen',
            field=models.CharField(blank=True, help_text='URL generada automáticamente', max_length=500),
        ),
    ]
