# Generated by Django 5.2.1 on 2025-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0009_add_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
