# Generated by Django 4.2.9 on 2025-06-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0010_alter_lugar_latitud_alter_lugar_longitud'),
    ]

    operations = []
