# Generated by Django 4.2.21 on 2025-06-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0011_entradadeblog_status_fotografia_status_lugar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadeblog',
            name='fecha_evento',
            field=models.DateField(blank=True, help_text='Fecha del evento/viaje. Si no se especifica día, usar el primer día del mes.', null=True),
        ),
        migrations.AddField(
            model_name='entradadeblog',
            name='mostrar_solo_mes_anio',
            field=models.BooleanField(default=False, help_text="Si está marcado, solo se mostrará 'mes año' (ej: 'mayo 2024'). Si no, se mostrará la fecha completa."),
        ),
        migrations.AddField(
            model_name='entradadeblog',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='lugar',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10),
        ),
    ]
