# Generated by Django 4.2.21 on 2025-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0012_entradadeblog_fecha_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadeblog',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable generada automáticamente desde el título. Ej: catedral-colonia', max_length=255, null=True, unique=True),
        ),
    ]
